services:
  frigate:
    build: .
    container_name: frigate-server
    ports:
      - "57001:57001"
    volumes:
      # Persistent storage for Frigate configuration and database
      - frigate-data:/home/frigate/.frigate
      # Mount Bitcoin Core data directory at expected location
      # - /bitcoin/.bitcoin:/home/frigate/.bitcoin:ro
    environment:
      # Network to use: mainnet, testnet, signet (default: mainnet)
      - FRIGATE_NETWORK=mainnet
      
      # Log level: trace, debug, info, warn, error (default: info)
      - FRIGATE_LOG_LEVEL=info
      
      # Custom Frigate home directory (default: /home/frigate/.frigate)
      # - FRIGATE_DIR=/custom/frigate/path

    restart: unless-stopped

volumes:
  frigate-data:
    driver: local

# The application creates a config file at /home/frigate/.frigate/config
# Default config example:
# {
#   "coreServer": "http://127.0.0.1:8332",
#   "coreAuthType": "COOKIE",              // "COOKIE" or "USERPASS"
#   "coreDataDir": "/home/frigate/.bitcoin",
#   "coreAuth": "bitcoin:password",
#   "startIndexing": true,
#   "indexStartHeight": 709632,            // Taproot activation height (mainnet)
#   "scriptPubKeyCacheSize": 10000000
# }
